### PR TITLE
Highlight null as a constant instead of as a keyword

### PR DESCRIPTION
**Pull request by arzg**
I put this as a PR because I think it’s highly subjective and want to make sure that you’re OK with the change.

### CODE REVIEW

**Comment by matklad** [comment]
I am fine either way, don't use languages with `null` a lot :-) Though, I am more accustomed to it being highlihgted as a keyword

**Comment by arzg** [comment]
> don't use languages with `null` a lot :-)

Same here ;)

> Though, I am more accustomed to it being highlihgted as a keyword

I’d personally say the same, but I think I’d prefer for Pale Fire to lean towards the direction of ‘correctness’ rather than what is familiar. For example, I recently made it so that `int` in C-family languages is highlighted as a primitive type, rather than a keyword – not what most people are used to, but what I would say is more ‘accurate’, if such a word can be applied to a theme :)

**Comment by matklad** [comment]
Well, in C, `int` *is* a keyword (unlike defines like `int32_t`), so there's both `keyword` and `type` highlighting are correct. When in doubt, I usually do like other JetBrains IDEs -- they know how to do semantic stuff better than anyone else. Looking at syntax highlighting of CLion, it seems they use keywords:

image

**Comment by arzg** [comment]
Fair enough – should I undo the change so that `int` and `char`, etc. are keywords again, and close this PR?

On the other hand, in Go, [`int` is not a keyword](https://golang.org/ref/spec#Keywords) – [it’s a _numeric type_](https://golang.org/ref/spec#Numeric_types) instead. In C# it looks like they’re undecided, as [they use the phrase ‘C# type/keyword’](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types). [`int` is a keyword in Java](https://en.wikipedia.org/wiki/List_of_Java_keywords), while [in Rust primitive types do not count as keywords](https://doc.rust-lang.org/reference/keywords.html).

IMHO it would be preferable to make a decision and highlight the same across the board for all languages, rather than highlighting primitive types differently based on the specifics of each language.

**Pull request closed without merging**
