### PR TITLE
friendly to python logical operator

### PR DESCRIPTION
**Pull request by WindSoilder**
Refer to: https://github.com/matklad/pale-fire/pull/2

### CODE REVIEW

**Comment by WindSoilder** [comment]
Hmm... I think it's better to make python `and` and `or` operator to be the same as `keyword` color, which make code easiler to read.
Screenshot:
图片

**Comment by arzg** [comment]
Yup, I agree with you, thanks for the PR! Would you mind running the generator so the theme files get updated?

**Comment by WindSoilder** [comment]
Ok, the theme files are updated :)

**Comment by arzg** [comment]
Thank you again :)

**Pull request merged**
