### PR TITLE
switch to modern vsce

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by lunacookies** [comment]
Is this good to merge?

**Comment by matklad** [comment]
Should be!

**Comment by lunacookies** [comment]
I don’t want to bother you for something as unimportant as this, but just to check: have you by any chance updated the marketplace token? If not then don’t worry, I just want to avoid spamming your email with another failed action notification :)

**Comment by matklad** [comment]
Refreshed!

**Comment by lunacookies** [comment]
perfect, thank you

**Pull request merged**
