### PR TITLE
Perceptually uniform colourscheme

### LINKED ISSUE #19: Future overengineering?
Hey @matklad, I’ve recently been thinking about some (possibly overengineered) changes I think might be nice for Pale Fire.

# Generation

I recently [fixed a bug](https://github.com/matklad/pale-fire/commit/26bc3c96abedd73f98bf7876fb0d2f7d0aa4dc4d) that arose from not having `"fontStyle": ""` somewhere. After fixing it I thought it might be a good idea to add this to every single rule so that:

1. the rules that _do_ have it don’t look strange (because there’s no reason you should look at `"fontStyle": ""` and think about why it’s there – it really doesn’t matter)
2. no such bugs can appear in the future

Rather than doing it manually, I thought it might be a good idea to use a generator program instead. [I’ve done this](https://github.com/arzg/noel/blob/6b4629943afd243177a146db6f20bd6838a6c691/src/main.rs) previously, and it worked really well. Another benefit of generating the theme is that colours can be synced between semantic and TextMate rules. The current approach of ‘hopefully remember to update both the semantic and TextMate colour’ has led to at least one [bug](https://github.com/matklad/pale-fire/commit/253d99804207e9f080b3aaa856ea559cf6ad4cb7).

# Colour palette harmonisation using fancy colour spaces

The Zenburn palette that Pale Fire uses has generated all its different colour variations through the RGB colour space. For example, here are `zenburn-green` and `zenburn-green+1`: 

Screen Shot 2020-10-25 at 11 12 26 pm
Screen Shot 2020-10-25 at 11 12 32 pm

Notice how the `H` and `S` values stay the same – only `V` changes.

The problem with this is that the movement along any one of these three dimensions does not appear smooth to humans. For example, take a look at the hue dimension (the colourful bar) – although this is only meant to be changing the hue, the blues look much darker than everything else, and the yellow looks less saturated than the other colours. To us, it appears as if the hue dimension is also affecting the other two dimensions. [This page](https://programmingdesignsystems.com/color/perceptually-uniform-color-spaces/) has some good examples of these kinds of problems arising in gradients.

Although physically the change in the photons is linear, it isn’t perceived as such by our visual system. This is something which HSV (along with HSL and CMYK) has inherited from sRGB.

This ‘perceptual non-uniformity’ can be fixed by using a colour space that has been deliberately warped so that it appears smooth to us, such as CIELAB or CIECAM02. [As far as I can tell](https://en.wikipedia.org/wiki/CIECAM02#CIECAM02_as_a_model_of_human_visual_processing), CIECAM02 is the state of the art in this field, but I’m just someone who’s done a bit of Googling and don’t know what any of the equations on that page mean :)

It’s hard to say whether this change would actually make the theme appear more harmonious without actually trying it, but I think it might be worth a shot.

# Combining the two

If the theme is being generated, why not generate the colour palette in the same program? This could allow changing, e.g. contrast by modifying the value of a single constant and running the generator. This idea is really appealing to me, as it allows changing the overall colours of the theme without having to manually change each value. Additionally, it would also allow fixing #10 by generating a second theme with increased contrast.

I know these changes are large and stray further from the original intention of this theme (port Emacs Zenburn to VS Code), which is why I wanted to ask you before actually trying to implement anything.

### PR DESCRIPTION
**Pull request by arzg**
This fixes #19.

I finally did it!

Here’s the before and after, showing how little has changed:

---

_before:_
Screen Shot 2021-01-07 at 7 16 54 pm

---

_after:_
Screen Shot 2021-01-07 at 7 16 11 pm

---

Hard to tell the difference, isn’t it?

I think a good demonstration of how easy it has now become to change the theme is in commit 959b2ae; in it I slightly darken the foreground text of the status bar, _including across different modes where the foreground colour changes,_ by changing a single number.

I’d say this PR is less about the actual change it’s making, but more about the flexibility it gives us to change the theme.

### CODE REVIEW

**Comment by matklad** [comment]
Let's bump the version in package.json?

lgtm!

**Comment by arzg** [comment]
> Let's bump the version in package.json?

Do you think this warrants a bump to `0.3`? 😄

> lgtm!

I’ve been waiting to do this for so long! I’m really happy that I finally got around to doing this, I can’t stop smiling :)

**Comment by matklad** [comment]
>Do you think this warrants a bump to 0.3? smile

yup!

**Comment by matklad** [comment]
Could you also add `sample.rs` and an updated screenshot? I've been thinking about the "withing" typo for like half a year already )

**Comment by arzg** [comment]
> Could you also add `sample.rs` and an updated screenshot? I've been thinking about the "withing" typo for like half a year already )

I was thinking that, since it’s so easy to change the colours now, it might be worth going through and tweaking all the colours. I’ve tried to keep the colours as close as possible in this PR (as you can tell from the screenshots), but I’ve had a few ideas for things that might be worth changing.

**Pull request merged**
